import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-dvh max-w-2xl mx-auto px-5 py-8" style={{ background: "var(--bg)" }}>
      <Link href="/" className="flex items-center gap-1.5 text-sm font-medium mb-6" style={{ color: "var(--brand)" }}>
        <ArrowLeft size={14} /> Back to Home
      </Link>
      <h1 className="text-2xl font-semibold mb-1" style={{ color: "var(--ink)" }}>Terms & Conditions</h1>
      <p className="text-sm mb-6" style={{ color: "var(--ink-muted)" }}>Last updated: May 2026 · POSTMAC VENTURES PRIVATE LIMITED</p>

      <div className="space-y-5 text-sm leading-relaxed" style={{ color: "var(--ink-soft)" }}>
        {[
          ["1. Parties", "These Terms & Conditions govern your use of InstantLoan (\"Platform\"), operated by POSTMAC VENTURES PRIVATE LIMITED, a company incorporated under the Companies Act 2013 (CIN: U66190HR2025PTC129138), with registered office at 3rd Floor, Orchid Center, Golf Course Road, Sector-53, DLF QE, Gurugram, Haryana – 122002 (\"Company\", \"we\", \"us\")."],
          ["2. Nature of Service", "InstantLoan is an unregulated loan eligibility assessment and aggregation marketplace. We are not a bank, NBFC, deposit-taking entity, or financial advisor. We do not lend money, guarantee loan approval, or influence bank credit decisions. We connect users with RBI-regulated scheduled commercial banks."],
          ["3. Fee & Payment", "A one-time non-refundable fee of ₹99 (or discounted amount applicable with a valid promo code) is charged for generating the AI eligibility report. Payment is processed by Razorpay Payment Solutions Pvt. Ltd., a PCI-DSS compliant payment gateway. GST (GSTIN: 06AAPCP5039G1Z7) is included in the displayed price."],
          ["4. No Guarantee of Approval", "Eligibility estimates are generated by AI based on your submitted information. Actual loan approval, interest rate, and disbursement are solely at the discretion of the lending bank. We make no warranty or representation regarding loan approval."],
          ["5. User Obligations", "You confirm that: (a) you are at least 18 years of age; (b) all information submitted is accurate and genuine; (c) you are the owner of the mobile number and bank account provided; (d) you will not use the platform for fraudulent purposes."],
          ["6. Data & Privacy", "Use of personal data is governed by our Privacy Policy. By using the platform you consent to processing of your data as described therein."],
          ["7. CIBIL & Credit Bureau", "Our eligibility check does not constitute a hard CIBIL enquiry. A hard enquiry is triggered only upon formal application submission to a bank and may affect your credit score."],
          ["8. Intellectual Property", "All content, branding, AI models, and software on this platform are the exclusive property of POSTMAC VENTURES PRIVATE LIMITED. Unauthorised reproduction is prohibited."],
          ["9. Limitation of Liability", "Our maximum liability to you in respect of any claim arising from your use of the platform is limited to the fee paid (₹99). We are not liable for loan rejection, interest rate changes, bank policy changes, or any consequential losses."],
          ["10. Governing Law & Jurisdiction", "These Terms are governed by the laws of the Republic of India. All disputes shall be subject to the exclusive jurisdiction of courts in Gurugram, Haryana."],
          ["11. Amendments", "We reserve the right to update these Terms at any time. Continued use of the platform after changes constitutes acceptance of the revised Terms."],
          ["12. Contact", "For legal notices: legal@instantloan.in | POSTMAC VENTURES PRIVATE LIMITED, 3rd Floor, Orchid Center, Golf Course Road, Gurugram, Haryana – 122002."],
        ].map(([title, body]) => (
          <div key={String(title)}>
            <h2 className="font-semibold mb-1" style={{ color: "var(--ink)" }}>{String(title)}</h2>
            <p>{String(body)}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
